name: telecom
channels:
  - defaults
dependencies:
  - python=3.6.8
  - pip=19.2.2
  - pip:
      - √==5.1.2
      - jupyter==1.0.0
      - pandas==1.0.3
      - matplotlib==3.2.1
      - sklearn==0.0
