name: telecom
channels:
  - defaults
dependencies:
  - python=3.6.8
  - pip=19.2.2
  - pip:
      - ipykernel==5.1.2
      - jupyter==1.0.0
      - pandas==1.0.3
      - matplotlib==3.2.1
      - sklearn==0.0
      - empiricaldist==0.6.0
      - seaborn==0.11.1
      - azureml==0.2.7
      - azureml-core==1.24.0
      - azureml-dataset-runtime==1.24.0
      - python-dotenv==0.15.0
      - azureml-widgets==1.24.0
      - azureml-pipeline==1.24.0
      - azureml-sdk==1.24.0
